// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  CABINET
// DateTime: 6/30/2016 10:04:38 PM
// UserName: Andrey
// Input file <Parser\Feel.Language.grammar.y - 6/30/2016 10:02:09 PM>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using Softengi.DmnEngine.Ast;

namespace Softengi.DmnEngine.Parser
{
internal enum Token {error=2,EOF=3,STRING=4,NAME=5,NUMBER=6,
    BOOLEAN=7,C_EQ=8,C_NE=9,C_LT=10,C_LE=11,C_GT=12,
    C_GE=13,OP_MINUS=14,OP_PLUS=15,OP_DIV=16,OP_MUL=17,OP_POW=18,
    P_OPEN=19,P_CLOSE=20,SP_OPEN=21,SP_CLOSE=22,CP_OPEN=23,CP_CLOSE=24,
    COMMA=25,DOT=26,COLON=27,RANGE=28,NULL=29,NOT=30,
    OR=31,AND=32,IN=33,BETWEEN=34,FOR=35,RETURN=36,
    IF=37,THEN=38,ELSE=39,SOME=40,EVERY=41,SATISFIES=42,
    INSTANCE=43,OF=44,FUNCTION=45,EXTERNAL=46,DATE=47,TIME=48,
    DURATION=49};

internal partial struct ValueType
{ 
			public decimal n; 
			public string s; 
			public bool b;
			public QualifiedName qn;

			public INode nd;
			public IExpression ex;
			public ILogical lg;

			public ComparisonOperator co;
			public QuantorOperator qo;

			public ExpressionList el;
	   }
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal partial class FeelParser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[128];
  private static State[] states = new State[65];
  private static string[] nonTerms = new string[] {
      "main", "endpoint", "literal", "simpleValue", "simpleLiteral", "numericLiteral", 
      "booleanLiteral", "stringLiteral", "dateTimeLiteral", "functionInvocation", 
      "expression", "textualExpression", "boxedExpression", "functionDefinition", 
      "forExpression", "ifExpression", "quantifiedExpression", "disjunction", 
      "conjunction", "arithmeticExpression", "pathExpression", "filterExpression", 
      "unaryTests", "positiveUnaryTests", "positiveUnaryTest", "simpleUnaryTests", 
      "simplePositiveUnaryTests", "simplePositiveUnaryTest", "instanceOf", "comparison", 
      "simpleExpressions", "simplePositiveUnaryTestOp", "comparisonOp", "quantorOp", 
      "intervalStart", "intervalEnd", "qualifiedName", "$accept", "textualExpressions", 
      "addition", "subtraction", "multiplication", "division", "exponentiation", 
      "arithmeticNegation", "simpleExpression", "closedIntervalStart", "closedIntervalEnd", 
      "parameters", "namedParameters", "expressionList", "namedParameter", "inParts", 
      "inPart", "contextEntries", "nameList", "contextEntry", "key", };

  static FeelParser() {
    states[0] = new State(new int[]{6,11,14,60,4,15,7,17,47,19,48,28,49,32,5,39,10,42,11,43,12,44,13,45,19,56,22,57,21,58,30,61},new int[]{-1,1,-26,3,-27,4,-28,59,-2,7,-4,8,-5,9,-6,10,-8,14,-7,16,-9,18,-37,36,-32,40,-35,46,-47,55});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{25,5,3,-50});
    states[5] = new State(new int[]{6,11,14,12,4,15,7,17,47,19,48,28,49,32,5,39,10,42,11,43,12,44,13,45,19,56,22,57,21,58},new int[]{-28,6,-2,7,-4,8,-5,9,-6,10,-8,14,-7,16,-9,18,-37,36,-32,40,-35,46,-47,55});
    states[6] = new State(-49);
    states[7] = new State(-33);
    states[8] = new State(-60);
    states[9] = new State(-61);
    states[10] = new State(-73);
    states[11] = new State(-79);
    states[12] = new State(new int[]{6,13});
    states[13] = new State(-80);
    states[14] = new State(-74);
    states[15] = new State(-77);
    states[16] = new State(-75);
    states[17] = new State(-78);
    states[18] = new State(-76);
    states[19] = new State(new int[]{19,20,32,23});
    states[20] = new State(new int[]{4,15},new int[]{-8,21});
    states[21] = new State(new int[]{20,22});
    states[22] = new State(-124);
    states[23] = new State(new int[]{48,24});
    states[24] = new State(new int[]{19,25});
    states[25] = new State(new int[]{4,15},new int[]{-8,26});
    states[26] = new State(new int[]{20,27});
    states[27] = new State(-126);
    states[28] = new State(new int[]{19,29});
    states[29] = new State(new int[]{4,15},new int[]{-8,30});
    states[30] = new State(new int[]{20,31});
    states[31] = new State(-125);
    states[32] = new State(new int[]{19,33});
    states[33] = new State(new int[]{4,15},new int[]{-8,34});
    states[34] = new State(new int[]{20,35});
    states[35] = new State(-127);
    states[36] = new State(new int[]{26,37,25,-62,3,-62,20,-62,28,-62,21,-62,22,-62});
    states[37] = new State(new int[]{5,38});
    states[38] = new State(-64);
    states[39] = new State(-63);
    states[40] = new State(new int[]{6,11,14,12,4,15,7,17,47,19,48,28,49,32,5,39},new int[]{-2,41,-4,8,-5,9,-6,10,-8,14,-7,16,-9,18,-37,36});
    states[41] = new State(-34);
    states[42] = new State(-36);
    states[43] = new State(-37);
    states[44] = new State(-38);
    states[45] = new State(-39);
    states[46] = new State(new int[]{6,11,14,12,4,15,7,17,47,19,48,28,49,32,5,39},new int[]{-2,47,-4,8,-5,9,-6,10,-8,14,-7,16,-9,18,-37,36});
    states[47] = new State(new int[]{28,48});
    states[48] = new State(new int[]{6,11,14,12,4,15,7,17,47,19,48,28,49,32,5,39},new int[]{-2,49,-4,8,-5,9,-6,10,-8,14,-7,16,-9,18,-37,36});
    states[49] = new State(new int[]{20,52,21,53,22,54},new int[]{-36,50,-48,51});
    states[50] = new State(-35);
    states[51] = new State(-44);
    states[52] = new State(-46);
    states[53] = new State(-47);
    states[54] = new State(-45);
    states[55] = new State(-40);
    states[56] = new State(-42);
    states[57] = new State(-43);
    states[58] = new State(-41);
    states[59] = new State(-48);
    states[60] = new State(new int[]{6,13,3,-52});
    states[61] = new State(new int[]{19,62});
    states[62] = new State(new int[]{6,11,14,12,4,15,7,17,47,19,48,28,49,32,5,39,10,42,11,43,12,44,13,45,19,56,22,57,21,58},new int[]{-27,63,-28,59,-2,7,-4,8,-5,9,-6,10,-8,14,-7,16,-9,18,-37,36,-32,40,-35,46,-47,55});
    states[63] = new State(new int[]{20,64,25,5});
    states[64] = new State(-51);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-38, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-26});
    rules[3] = new Rule(-11, new int[]{-12});
    rules[4] = new Rule(-11, new int[]{-13});
    rules[5] = new Rule(-12, new int[]{-14});
    rules[6] = new Rule(-12, new int[]{-15});
    rules[7] = new Rule(-12, new int[]{-16});
    rules[8] = new Rule(-12, new int[]{-17});
    rules[9] = new Rule(-12, new int[]{-18});
    rules[10] = new Rule(-12, new int[]{-19});
    rules[11] = new Rule(-12, new int[]{-30});
    rules[12] = new Rule(-12, new int[]{-20});
    rules[13] = new Rule(-12, new int[]{-29});
    rules[14] = new Rule(-12, new int[]{-21});
    rules[15] = new Rule(-12, new int[]{-22});
    rules[16] = new Rule(-12, new int[]{-10});
    rules[17] = new Rule(-12, new int[]{-3});
    rules[18] = new Rule(-12, new int[]{-28});
    rules[19] = new Rule(-12, new int[]{5});
    rules[20] = new Rule(-12, new int[]{19,-12,20});
    rules[21] = new Rule(-39, new int[]{-12});
    rules[22] = new Rule(-39, new int[]{-39,25,-12});
    rules[23] = new Rule(-20, new int[]{-40});
    rules[24] = new Rule(-20, new int[]{-41});
    rules[25] = new Rule(-20, new int[]{-42});
    rules[26] = new Rule(-20, new int[]{-43});
    rules[27] = new Rule(-20, new int[]{-44});
    rules[28] = new Rule(-20, new int[]{-45});
    rules[29] = new Rule(-46, new int[]{-20});
    rules[30] = new Rule(-46, new int[]{-4});
    rules[31] = new Rule(-31, new int[]{-46});
    rules[32] = new Rule(-31, new int[]{-31,25,-46});
    rules[33] = new Rule(-28, new int[]{-2});
    rules[34] = new Rule(-28, new int[]{-32,-2});
    rules[35] = new Rule(-28, new int[]{-35,-2,28,-2,-36});
    rules[36] = new Rule(-32, new int[]{10});
    rules[37] = new Rule(-32, new int[]{11});
    rules[38] = new Rule(-32, new int[]{12});
    rules[39] = new Rule(-32, new int[]{13});
    rules[40] = new Rule(-35, new int[]{-47});
    rules[41] = new Rule(-35, new int[]{21});
    rules[42] = new Rule(-47, new int[]{19});
    rules[43] = new Rule(-47, new int[]{22});
    rules[44] = new Rule(-36, new int[]{-48});
    rules[45] = new Rule(-36, new int[]{22});
    rules[46] = new Rule(-48, new int[]{20});
    rules[47] = new Rule(-48, new int[]{21});
    rules[48] = new Rule(-27, new int[]{-28});
    rules[49] = new Rule(-27, new int[]{-27,25,-28});
    rules[50] = new Rule(-26, new int[]{-27});
    rules[51] = new Rule(-26, new int[]{30,19,-27,20});
    rules[52] = new Rule(-26, new int[]{14});
    rules[53] = new Rule(-25, new int[]{-28});
    rules[54] = new Rule(-25, new int[]{29});
    rules[55] = new Rule(-24, new int[]{-25});
    rules[56] = new Rule(-24, new int[]{-24,25,-25});
    rules[57] = new Rule(-23, new int[]{-24});
    rules[58] = new Rule(-23, new int[]{30,19,-24,20});
    rules[59] = new Rule(-23, new int[]{14});
    rules[60] = new Rule(-2, new int[]{-4});
    rules[61] = new Rule(-4, new int[]{-5});
    rules[62] = new Rule(-4, new int[]{-37});
    rules[63] = new Rule(-37, new int[]{5});
    rules[64] = new Rule(-37, new int[]{-37,26,5});
    rules[65] = new Rule(-40, new int[]{-11,15,-11});
    rules[66] = new Rule(-41, new int[]{-11,14,-11});
    rules[67] = new Rule(-42, new int[]{-11,17,-11});
    rules[68] = new Rule(-43, new int[]{-11,16,-11});
    rules[69] = new Rule(-44, new int[]{-11,18,-11});
    rules[70] = new Rule(-45, new int[]{14,-11});
    rules[71] = new Rule(-3, new int[]{-5});
    rules[72] = new Rule(-3, new int[]{29});
    rules[73] = new Rule(-5, new int[]{-6});
    rules[74] = new Rule(-5, new int[]{-8});
    rules[75] = new Rule(-5, new int[]{-7});
    rules[76] = new Rule(-5, new int[]{-9});
    rules[77] = new Rule(-8, new int[]{4});
    rules[78] = new Rule(-7, new int[]{7});
    rules[79] = new Rule(-6, new int[]{6});
    rules[80] = new Rule(-6, new int[]{14,6});
    rules[81] = new Rule(-10, new int[]{-11,-49});
    rules[82] = new Rule(-49, new int[]{19,-50,20});
    rules[83] = new Rule(-49, new int[]{19,-51,20});
    rules[84] = new Rule(-50, new int[]{-52});
    rules[85] = new Rule(-50, new int[]{-50,25,-52});
    rules[86] = new Rule(-52, new int[]{5,27,-11});
    rules[87] = new Rule(-21, new int[]{-11,26,5});
    rules[88] = new Rule(-15, new int[]{35,-53,36,-11});
    rules[89] = new Rule(-16, new int[]{37,-11,38,-11,39,-11});
    rules[90] = new Rule(-17, new int[]{-34,5,33,-53,42,-11});
    rules[91] = new Rule(-34, new int[]{40});
    rules[92] = new Rule(-34, new int[]{41});
    rules[93] = new Rule(-53, new int[]{-54});
    rules[94] = new Rule(-53, new int[]{-53,25,-54});
    rules[95] = new Rule(-54, new int[]{5,33,-11});
    rules[96] = new Rule(-18, new int[]{-11,31,-11});
    rules[97] = new Rule(-19, new int[]{-11,32,-11});
    rules[98] = new Rule(-30, new int[]{-11,-33,-11});
    rules[99] = new Rule(-30, new int[]{-11,34,-11,32,-11});
    rules[100] = new Rule(-30, new int[]{-11,33,-24});
    rules[101] = new Rule(-30, new int[]{-11,33,19,-24,20});
    rules[102] = new Rule(-33, new int[]{9});
    rules[103] = new Rule(-33, new int[]{8});
    rules[104] = new Rule(-33, new int[]{10});
    rules[105] = new Rule(-33, new int[]{11});
    rules[106] = new Rule(-33, new int[]{12});
    rules[107] = new Rule(-33, new int[]{13});
    rules[108] = new Rule(-22, new int[]{-11,21,-11,22});
    rules[109] = new Rule(-29, new int[]{-11,43,44,-37});
    rules[110] = new Rule(-13, new int[]{21,-51,22});
    rules[111] = new Rule(-13, new int[]{23,-55,24});
    rules[112] = new Rule(-13, new int[]{-14});
    rules[113] = new Rule(-51, new int[]{-11});
    rules[114] = new Rule(-51, new int[]{-51,25,-11});
    rules[115] = new Rule(-14, new int[]{45,19,-56,20,-11});
    rules[116] = new Rule(-14, new int[]{45,19,-56,20,46,-11});
    rules[117] = new Rule(-56, new int[]{5});
    rules[118] = new Rule(-56, new int[]{-56,25,5});
    rules[119] = new Rule(-55, new int[]{-57});
    rules[120] = new Rule(-55, new int[]{-55,25,-57});
    rules[121] = new Rule(-57, new int[]{-58,27,-11});
    rules[122] = new Rule(-58, new int[]{5});
    rules[123] = new Rule(-58, new int[]{-8});
    rules[124] = new Rule(-9, new int[]{47,19,-8,20});
    rules[125] = new Rule(-9, new int[]{48,19,-8,20});
    rules[126] = new Rule(-9, new int[]{47,32,48,19,-8,20});
    rules[127] = new Rule(-9, new int[]{49,19,-8,20});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Token.error, (int)Token.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // main -> simpleUnaryTests
{ Debug("main/simpleUnaryTests");	Root = ValueStack[ValueStack.Depth-1].lg; }
        break;
      case 3: // expression -> textualExpression
{ Debug("expression/text");	CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 4: // expression -> boxedExpression
{ Debug("expression/box");	CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 5: // textualExpression -> functionDefinition
{ Debug("textualExpression/funDef");	CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 6: // textualExpression -> forExpression
{ Debug("textualExpression/for");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 7: // textualExpression -> ifExpression
{ Debug("textualExpression/if");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 8: // textualExpression -> quantifiedExpression
{ Debug("textualExpression/quan");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 9: // textualExpression -> disjunction
{ Debug("textualExpression/disj");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 10: // textualExpression -> conjunction
{ Debug("textualExpression/conj");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 11: // textualExpression -> comparison
{ Debug("textualExpression/comp");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].lg; }
        break;
      case 12: // textualExpression -> arithmeticExpression
{ Debug("textualExpression/arith");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 13: // textualExpression -> instanceOf
{ Debug("textualExpression/inst");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].lg; }
        break;
      case 14: // textualExpression -> pathExpression
{ Debug("textualExpression/path");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 15: // textualExpression -> filterExpression
{ Debug("textualExpression/filt");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 16: // textualExpression -> functionInvocation
{ Debug("textualExpression/funInv");	CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 17: // textualExpression -> literal
{ Debug("textualExpression/lit");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 18: // textualExpression -> simplePositiveUnaryTest
{ Debug("textualExpression/spUT");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].lg; }
        break;
      case 19: // textualExpression -> NAME
{ Debug("textualExpression/name");		CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 20: // textualExpression -> P_OPEN, textualExpression, P_CLOSE
{ Debug("textualExpression/braces");	CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-2].ex; }
        break;
      case 21: // textualExpressions -> textualExpression
{ Debug("textualExpressions");	 CurrentSemanticValue = ValueStack[ValueStack.Depth-1].ex;			  }
        break;
      case 22: // textualExpressions -> textualExpressions, COMMA, textualExpression
{ Debug("textualExpressions/,"); CurrentSemanticValue = new Or(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 23: // arithmeticExpression -> addition
{ Debug("arithmeticExpression/add"); CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1]; }
        break;
      case 24: // arithmeticExpression -> subtraction
{ Debug("arithmeticExpression/sub"); CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1]; }
        break;
      case 25: // arithmeticExpression -> multiplication
{ Debug("arithmeticExpression/mul"); CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1]; }
        break;
      case 26: // arithmeticExpression -> division
{ Debug("arithmeticExpression/div"); CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1]; }
        break;
      case 27: // arithmeticExpression -> exponentiation
{ Debug("arithmeticExpression/pow"); CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1]; }
        break;
      case 28: // arithmeticExpression -> arithmeticNegation
{ Debug("arithmeticExpression/neg"); CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1]; }
        break;
      case 29: // simpleExpression -> arithmeticExpression
{ Debug("simpleExpression/arith");	CurrentSemanticValue = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 30: // simpleExpression -> simpleValue
{ Debug("simpleExpression/simVal");	CurrentSemanticValue = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 31: // simpleExpressions -> simpleExpression
{ Debug("simpleExpressions");	CurrentSemanticValue.el = new ExpressionList(); CurrentSemanticValue.el.Add(ValueStack[ValueStack.Depth-1]); }
        break;
      case 32: // simpleExpressions -> simpleExpressions, COMMA, simpleExpression
{ Debug("simpleExpressions/,"); CurrentSemanticValue.el = ValueStack[ValueStack.Depth-3].el;				   CurrentSemanticValue.el.Add(ValueStack[ValueStack.Depth-1]); }
        break;
      case 33: // simplePositiveUnaryTest -> endpoint
{ Debug("simplePositiveUnaryTest");		CurrentSemanticValue.lg = new Comparison(ComparisonOperator.Equal, new InputValue(), ValueStack[ValueStack.Depth-1].nd); }
        break;
      case 34: // simplePositiveUnaryTest -> simplePositiveUnaryTestOp, endpoint
{ Debug("simplePositiveUnaryTest/cmp");	CurrentSemanticValue.lg = new Comparison(ValueStack[ValueStack.Depth-2].co, new InputValue(), ValueStack[ValueStack.Depth-1].nd);						 }
        break;
      case 35: // simplePositiveUnaryTest -> intervalStart, endpoint, RANGE, endpoint, 
               //                            intervalEnd
{ Debug("simplePositiveUnaryTest/rng");	CurrentSemanticValue.lg = new Range(ValueStack[ValueStack.Depth-5].b, ValueStack[ValueStack.Depth-1].b, ValueStack[ValueStack.Depth-4].nd, ValueStack[ValueStack.Depth-2].nd, new InputValue());					 }
        break;
      case 36: // simplePositiveUnaryTestOp -> C_LT
{ CurrentSemanticValue.co = ComparisonOperator.LessThan;			  }
        break;
      case 37: // simplePositiveUnaryTestOp -> C_LE
{ CurrentSemanticValue.co = ComparisonOperator.LessThanOrEqual;	  }
        break;
      case 38: // simplePositiveUnaryTestOp -> C_GT
{ CurrentSemanticValue.co = ComparisonOperator.GreaterThan;		  }
        break;
      case 39: // simplePositiveUnaryTestOp -> C_GE
{ CurrentSemanticValue.co = ComparisonOperator.GreaterThanOrEqual; }
        break;
      case 40: // intervalStart -> closedIntervalStart
{ CurrentSemanticValue.b = false; }
        break;
      case 41: // intervalStart -> SP_OPEN
{ CurrentSemanticValue.b = true;  }
        break;
      case 44: // intervalEnd -> closedIntervalEnd
{ CurrentSemanticValue.b = false; }
        break;
      case 45: // intervalEnd -> SP_CLOSE
{ CurrentSemanticValue.b = true;  }
        break;
      case 48: // simplePositiveUnaryTests -> simplePositiveUnaryTest
{ Debug("simplePositiveUnaryTests");	CurrentSemanticValue.lg = ValueStack[ValueStack.Depth-1].lg;			 }
        break;
      case 49: // simplePositiveUnaryTests -> simplePositiveUnaryTests, COMMA, 
               //                             simplePositiveUnaryTest
{ Debug("simplePositiveUnaryTests/,");	CurrentSemanticValue.lg = new Or(ValueStack[ValueStack.Depth-3].lg, ValueStack[ValueStack.Depth-1].lg); }
        break;
      case 50: // simpleUnaryTests -> simplePositiveUnaryTests
{ Debug("simpleUnaryTests");		CurrentSemanticValue.lg = ValueStack[ValueStack.Depth-1].lg;						}
        break;
      case 51: // simpleUnaryTests -> NOT, P_OPEN, simplePositiveUnaryTests, P_CLOSE
{ Debug("simpleUnaryTests/not");	CurrentSemanticValue.lg = new Not(ValueStack[ValueStack.Depth-2].lg);				}
        break;
      case 52: // simpleUnaryTests -> OP_MINUS
{ Debug("simpleUnaryTests/-");		CurrentSemanticValue.lg = new BooleanLiteral(true);	}
        break;
      case 55: // positiveUnaryTests -> positiveUnaryTest
{ Debug("positiveUnaryTests");	 CurrentSemanticValue.lg = ValueStack[ValueStack.Depth-1].lg;			  }
        break;
      case 56: // positiveUnaryTests -> positiveUnaryTests, COMMA, positiveUnaryTest
{ Debug("positiveUnaryTests/,"); CurrentSemanticValue.lg = new Or(ValueStack[ValueStack.Depth-3].lg, ValueStack[ValueStack.Depth-1].lg); }
        break;
      case 57: // unaryTests -> positiveUnaryTests
{ Debug("unaryTests");		CurrentSemanticValue.lg = ValueStack[ValueStack.Depth-1].lg;					   }
        break;
      case 58: // unaryTests -> NOT, P_OPEN, positiveUnaryTests, P_CLOSE
{ Debug("unaryTests/not");	CurrentSemanticValue.lg = new Not(ValueStack[ValueStack.Depth-2].lg);			   }
        break;
      case 59: // unaryTests -> OP_MINUS
{ Debug("unaryTests/-");	CurrentSemanticValue.lg = new BooleanLiteral(true); }
        break;
      case 60: // endpoint -> simpleValue
{ Debug("endpoint/value"); CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 61: // simpleValue -> simpleLiteral
{ Debug("simpleValue/lit");	CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 62: // simpleValue -> qualifiedName
{ Debug("simpleValue/qn");	CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].qn; }
        break;
      case 63: // qualifiedName -> NAME
{ CurrentSemanticValue.qn = new QualifiedName(ValueStack[ValueStack.Depth-1].s);		}
        break;
      case 64: // qualifiedName -> qualifiedName, DOT, NAME
{ CurrentSemanticValue.qn = ValueStack[ValueStack.Depth-3].qn;	CurrentSemanticValue.qn.AddComponent(ValueStack[ValueStack.Depth-1].s);	}
        break;
      case 65: // addition -> expression, OP_PLUS, expression
{ Debug("add"); CurrentSemanticValue = new Add(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 66: // subtraction -> expression, OP_MINUS, expression
{ Debug("sub"); CurrentSemanticValue = new Sub(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 67: // multiplication -> expression, OP_MUL, expression
{ Debug("mul"); CurrentSemanticValue = new Mul(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 68: // division -> expression, OP_DIV, expression
{ Debug("div"); CurrentSemanticValue = new Div(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 69: // exponentiation -> expression, OP_POW, expression
{ Debug("pow"); CurrentSemanticValue = new Pow(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 70: // arithmeticNegation -> OP_MINUS, expression
{ Debug("neg"); CurrentSemanticValue = new Neg(ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 71: // literal -> simpleLiteral
{ Debug("literal/simLit");	CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 72: // literal -> NULL
{ Debug("literal/null");	CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1]; }
        break;
      case 73: // simpleLiteral -> numericLiteral
{ Debug("simpleLiteral/num");	CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 74: // simpleLiteral -> stringLiteral
{ Debug("simpleLiteral/str");	CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 75: // simpleLiteral -> booleanLiteral
{ Debug("simpleLiteral/bool");	CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 76: // simpleLiteral -> dateTimeLiteral
{ Debug("simpleLiteral/dt");	CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 77: // stringLiteral -> STRING
{ CurrentSemanticValue.nd = new StringLiteral(ValueStack[ValueStack.Depth-1].s); }
        break;
      case 78: // booleanLiteral -> BOOLEAN
{ CurrentSemanticValue.nd = new BooleanLiteral(ValueStack[ValueStack.Depth-1].b); }
        break;
      case 79: // numericLiteral -> NUMBER
{ Debug("numericLiteral");     CurrentSemanticValue.nd = new NumericLiteral( ValueStack[ValueStack.Depth-1].n); }
        break;
      case 80: // numericLiteral -> OP_MINUS, NUMBER
{ Debug("numericLiteral/neg"); CurrentSemanticValue.nd = new NumericLiteral(-ValueStack[ValueStack.Depth-1].n); }
        break;
      case 81: // functionInvocation -> expression, parameters
{ Debug("functionInvocation");	CurrentSemanticValue.nd = new FunctionInvocation(ValueStack[ValueStack.Depth-2].ex, ValueStack[ValueStack.Depth-1]); }
        break;
      case 82: // parameters -> P_OPEN, namedParameters, P_CLOSE
{ Debug("parameters/named");	CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
        break;
      case 83: // parameters -> P_OPEN, expressionList, P_CLOSE
{ Debug("parameters/pos");		CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
        break;
      case 84: // namedParameters -> namedParameter
{ Debug("namedParameters");	  CurrentSemanticValue = new NamedParameterList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 85: // namedParameters -> namedParameters, COMMA, namedParameter
{ Debug("namedParameters/,"); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; CurrentSemanticValue.Add(ValueStack[ValueStack.Depth-1]);			   }
        break;
      case 86: // namedParameter -> NAME, COLON, expression
{ Debug("namedParameter");	  CurrentSemanticValue = new NamedParam(ValueStack[ValueStack.Depth-3].s, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 87: // pathExpression -> expression, DOT, NAME
{ Debug("pathExpression"); CurrentSemanticValue.ex = new PathExpression(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].s); }
        break;
      case 88: // forExpression -> FOR, inParts, RETURN, expression
{ Debug("forExpression");  CurrentSemanticValue.ex = new For(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 89: // ifExpression -> IF, expression, THEN, expression, ELSE, expression
{ Debug("ifExpression");  CurrentSemanticValue.ex = new If(ValueStack[ValueStack.Depth-5].ex, ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 90: // quantifiedExpression -> quantorOp, NAME, IN, inParts, SATISFIES, expression
{ Debug("quantifiedExpression");  CurrentSemanticValue.ex = new QuantifiedExpression(ValueStack[ValueStack.Depth-6].qo, ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 91: // quantorOp -> SOME
{ CurrentSemanticValue.qo = QuantorOperator.Some;  }
        break;
      case 92: // quantorOp -> EVERY
{ CurrentSemanticValue.qo = QuantorOperator.Every; }
        break;
      case 93: // inParts -> inPart
{ Debug("inParts");   CurrentSemanticValue = new InPartList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 94: // inParts -> inParts, COMMA, inPart
{ Debug("inParts/,"); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; CurrentSemanticValue.Add(ValueStack[ValueStack.Depth-1]);	   }
        break;
      case 95: // inPart -> NAME, IN, expression
{ Debug("inPart");   CurrentSemanticValue = new InPart(ValueStack[ValueStack.Depth-3].s, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 96: // disjunction -> expression, OR, expression
{ Debug("disjunction");  CurrentSemanticValue.ex = new Or(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 97: // conjunction -> expression, AND, expression
{ Debug("conjunction");  CurrentSemanticValue.ex = new And(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 98: // comparison -> expression, comparisonOp, expression
{ Debug("comparision/cmp");	 CurrentSemanticValue.lg = new Comparison(ValueStack[ValueStack.Depth-2].co, ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex);		 }
        break;
      case 99: // comparison -> expression, BETWEEN, expression, AND, expression
{ Debug("comparision/btw");	 CurrentSemanticValue.lg = new Range(true, true, ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-5].ex); }
        break;
      case 100: // comparison -> expression, IN, positiveUnaryTests
{ Debug("comparision/in");	 CurrentSemanticValue.lg = new In(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].lg);					 }
        break;
      case 101: // comparison -> expression, IN, P_OPEN, positiveUnaryTests, P_CLOSE
{ Debug("comparision/P_in"); CurrentSemanticValue.lg = new In(ValueStack[ValueStack.Depth-5].ex, ValueStack[ValueStack.Depth-2].lg);					 }
        break;
      case 102: // comparisonOp -> C_NE
{ CurrentSemanticValue.co = ComparisonOperator.NotEqual;			  }
        break;
      case 103: // comparisonOp -> C_EQ
{ CurrentSemanticValue.co = ComparisonOperator.Equal;			  }
        break;
      case 104: // comparisonOp -> C_LT
{ CurrentSemanticValue.co = ComparisonOperator.LessThan;			  }
        break;
      case 105: // comparisonOp -> C_LE
{ CurrentSemanticValue.co = ComparisonOperator.LessThanOrEqual;	  }
        break;
      case 106: // comparisonOp -> C_GT
{ CurrentSemanticValue.co = ComparisonOperator.GreaterThan;		  }
        break;
      case 107: // comparisonOp -> C_GE
{ CurrentSemanticValue.co = ComparisonOperator.GreaterThanOrEqual; }
        break;
      case 108: // filterExpression -> expression, SP_OPEN, expression, SP_CLOSE
{ Debug("filterExpression"); CurrentSemanticValue.ex = new Filter(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].ex); }
        break;
      case 109: // instanceOf -> expression, INSTANCE, OF, qualifiedName
{ Debug("instanceOf"); CurrentSemanticValue.lg = new InstanceOf(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-1].qn); }
        break;
      case 110: // boxedExpression -> SP_OPEN, expressionList, SP_CLOSE
{ Debug("boxedExpression/list");	CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-2]; }
        break;
      case 111: // boxedExpression -> CP_OPEN, contextEntries, CP_CLOSE
{ Debug("boxedExpression/context"); CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-2]; }
        break;
      case 112: // boxedExpression -> functionDefinition
{ Debug("boxedExpression/funDef");  CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 113: // expressionList -> expression
{ Debug("expressionList");   CurrentSemanticValue = new ExpressionList(ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 114: // expressionList -> expressionList, COMMA, expression
{ Debug("expressionList/,"); CurrentSemanticValue = ValueStack[ValueStack.Depth-3];		  CurrentSemanticValue.Add(ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 117: // nameList -> NAME
{ Debug("formatParameterList");   CurrentSemanticValue = new nameList(ValueStack[ValueStack.Depth-1].s); }
        break;
      case 118: // nameList -> nameList, COMMA, NAME
{ Debug("formatParameterList/,"); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; CurrentSemanticValue.Add(ValueStack[ValueStack.Depth-1].s);	 }
        break;
      case 119: // contextEntries -> contextEntry
{ Debug("contextEntries/,"); CurrentSemanticValue = new ContextEntryList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 120: // contextEntries -> contextEntries, COMMA, contextEntry
{ Debug("contextEntries/,"); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; CurrentSemanticValue.Add(ValueStack[ValueStack.Depth-1]);			}
        break;
      case 121: // contextEntry -> key, COLON, expression
{ Debug("contextEntry");	CurrentSemanticValue = new KeyValue(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1].ex); }
        break;
      case 122: // key -> NAME
{ Debug("key/name");	CurrentSemanticValue = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 123: // key -> stringLiteral
{ Debug("key/strLit");	CurrentSemanticValue = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 124: // dateTimeLiteral -> DATE, P_OPEN, stringLiteral, P_CLOSE
{ CurrentSemanticValue.nd = DateTimeLiteral.ParseDate(((StringLiteral) ValueStack[ValueStack.Depth-2].nd).Value);		 }
        break;
      case 125: // dateTimeLiteral -> TIME, P_OPEN, stringLiteral, P_CLOSE
{ CurrentSemanticValue.nd = DateTimeLiteral.ParseTime(((StringLiteral) ValueStack[ValueStack.Depth-2].nd).Value);		 }
        break;
      case 126: // dateTimeLiteral -> DATE, AND, TIME, P_OPEN, stringLiteral, P_CLOSE
{ CurrentSemanticValue.nd = DateTimeLiteral.ParseDateAndTime(((StringLiteral) ValueStack[ValueStack.Depth-2].nd).Value); }
        break;
      case 127: // dateTimeLiteral -> DURATION, P_OPEN, stringLiteral, P_CLOSE
{ CurrentSemanticValue.nd = TimeSpanLiteral.Parse(((StringLiteral) ValueStack[ValueStack.Depth-2].nd).Value);			 }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Token)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Token)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


// The use code section.
// It is empty, because use code goes in a partial class.
}
}
