// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  CABINET
// DateTime: 6/27/2016 11:20:02 AM
// UserName: Andrey
// Input file <Sfeel\Parser\SFeel.Language.grammar.y - 6/27/2016 11:19:16 AM>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using Softengi.DmnEngine.SFeel.Ast;

namespace Softengi.DmnEngine.SFeel.Parser
{
internal enum Token {error=2,EOF=3,STRING=4,NAME=5,NUMBER=6,
    BOOLEAN=7,C_EQ=8,C_LT=9,C_LE=10,C_GT=11,C_GE=12,
    OP_MINUS=13,OP_PLUS=14,OP_DIV=15,OP_MUL=16,OP_POW=17,P_OPEN=18,
    P_CLOSE=19,SP_OPEN=20,SP_CLOSE=21,COMMA=22,DOT=23,RANGE=24,
    NOT=25};

internal partial struct ValueType
{ 
			public decimal n; 
			public string s; 
			public bool b;

			public INode nd;
			public QualifiedName qn;
			public ILogical lg;

			public ComparisonOperator co;
	   }
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal partial class SFeelParser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[49];
  private static State[] states = new State[44];
  private static string[] nonTerms = new string[] {
      "main", "simpleUnaryTests", "simplePositiveUnaryTests", "simplePositiveUnaryTest", 
      "endpoint", "simpleValue", "simpleLiteral", "numericLiteral", "booleanLiteral", 
      "stringLiteral", "simplePositiveUnaryTestOp", "intervalStart", "intervalEnd", 
      "qualifiedName", "$accept", "openIntervalStart", "openIntervalEnd", };

  static SFeelParser() {
    states[0] = new State(new int[]{9,21,10,22,11,23,12,24,18,35,21,36,20,37,13,39,25,40,3,-2,22,-7,6,-14,4,-14,7,-14,5,-14,23,-14,24,-14},new int[]{-1,1,-2,3,-3,4,-4,38,-11,7,-12,25,-16,34});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(-3);
    states[4] = new State(new int[]{22,5,3,-5});
    states[5] = new State(new int[]{9,21,10,22,11,23,12,24,18,35,21,36,20,37,22,-11,3,-11,19,-11,6,-14,4,-14,7,-14,5,-14,23,-14,24,-14},new int[]{-4,6,-11,7,-12,25,-16,34});
    states[6] = new State(-9);
    states[7] = new State(new int[]{6,12,4,14,7,16,5,20,22,-31,3,-31,19,-31,23,-46},new int[]{-5,8,-6,9,-7,10,-8,11,-10,13,-9,15,-14,17});
    states[8] = new State(-12);
    states[9] = new State(-32);
    states[10] = new State(-34);
    states[11] = new State(-37);
    states[12] = new State(-41);
    states[13] = new State(-38);
    states[14] = new State(-43);
    states[15] = new State(-39);
    states[16] = new State(-45);
    states[17] = new State(new int[]{23,18,22,-35,3,-35,19,-35,24,-35,20,-35,21,-35});
    states[18] = new State(new int[]{5,19});
    states[19] = new State(-48);
    states[20] = new State(-47);
    states[21] = new State(-27);
    states[22] = new State(-28);
    states[23] = new State(-29);
    states[24] = new State(-30);
    states[25] = new State(new int[]{6,12,4,14,7,16,5,20,24,-31,23,-46},new int[]{-5,26,-6,9,-7,10,-8,11,-10,13,-9,15,-14,17});
    states[26] = new State(new int[]{24,27});
    states[27] = new State(new int[]{6,12,4,14,7,16,5,20,19,-31,20,-31,21,-31,22,-31,3,-31,23,-46},new int[]{-5,28,-6,9,-7,10,-8,11,-10,13,-9,15,-14,17});
    states[28] = new State(new int[]{19,31,20,32,21,33,22,-20,3,-20},new int[]{-13,29,-17,30});
    states[29] = new State(-13);
    states[30] = new State(-21);
    states[31] = new State(-24);
    states[32] = new State(-25);
    states[33] = new State(-22);
    states[34] = new State(-15);
    states[35] = new State(-18);
    states[36] = new State(-19);
    states[37] = new State(-16);
    states[38] = new State(-8);
    states[39] = new State(-10);
    states[40] = new State(new int[]{18,41});
    states[41] = new State(new int[]{9,21,10,22,11,23,12,24,18,35,21,36,20,37,13,39,19,-7,22,-7,6,-14,4,-14,7,-14,5,-14,23,-14,24,-14},new int[]{-3,42,-4,38,-11,7,-12,25,-16,34});
    states[42] = new State(new int[]{19,43,22,5});
    states[43] = new State(-6);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-15, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{});
    rules[3] = new Rule(-1, new int[]{-2});
    rules[4] = new Rule(-2, new int[]{});
    rules[5] = new Rule(-2, new int[]{-3});
    rules[6] = new Rule(-2, new int[]{25,18,-3,19});
    rules[7] = new Rule(-3, new int[]{});
    rules[8] = new Rule(-3, new int[]{-4});
    rules[9] = new Rule(-3, new int[]{-3,22,-4});
    rules[10] = new Rule(-3, new int[]{13});
    rules[11] = new Rule(-4, new int[]{});
    rules[12] = new Rule(-4, new int[]{-11,-5});
    rules[13] = new Rule(-4, new int[]{-12,-5,24,-5,-13});
    rules[14] = new Rule(-12, new int[]{});
    rules[15] = new Rule(-12, new int[]{-16});
    rules[16] = new Rule(-12, new int[]{20});
    rules[17] = new Rule(-16, new int[]{});
    rules[18] = new Rule(-16, new int[]{18});
    rules[19] = new Rule(-16, new int[]{21});
    rules[20] = new Rule(-13, new int[]{});
    rules[21] = new Rule(-13, new int[]{-17});
    rules[22] = new Rule(-13, new int[]{21});
    rules[23] = new Rule(-17, new int[]{});
    rules[24] = new Rule(-17, new int[]{19});
    rules[25] = new Rule(-17, new int[]{20});
    rules[26] = new Rule(-11, new int[]{});
    rules[27] = new Rule(-11, new int[]{9});
    rules[28] = new Rule(-11, new int[]{10});
    rules[29] = new Rule(-11, new int[]{11});
    rules[30] = new Rule(-11, new int[]{12});
    rules[31] = new Rule(-5, new int[]{});
    rules[32] = new Rule(-5, new int[]{-6});
    rules[33] = new Rule(-6, new int[]{});
    rules[34] = new Rule(-6, new int[]{-7});
    rules[35] = new Rule(-6, new int[]{-14});
    rules[36] = new Rule(-7, new int[]{});
    rules[37] = new Rule(-7, new int[]{-8});
    rules[38] = new Rule(-7, new int[]{-10});
    rules[39] = new Rule(-7, new int[]{-9});
    rules[40] = new Rule(-8, new int[]{});
    rules[41] = new Rule(-8, new int[]{6});
    rules[42] = new Rule(-10, new int[]{});
    rules[43] = new Rule(-10, new int[]{4});
    rules[44] = new Rule(-9, new int[]{});
    rules[45] = new Rule(-9, new int[]{7});
    rules[46] = new Rule(-14, new int[]{});
    rules[47] = new Rule(-14, new int[]{5});
    rules[48] = new Rule(-14, new int[]{-14,23,5});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Token.error, (int)Token.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 3: // main -> simpleUnaryTests
{ Root = ValueStack[ValueStack.Depth-1].lg; }
        break;
      case 5: // simpleUnaryTests -> simplePositiveUnaryTests
{ CurrentSemanticValue.lg = ValueStack[ValueStack.Depth-1].lg;			}
        break;
      case 6: // simpleUnaryTests -> NOT, P_OPEN, simplePositiveUnaryTests, P_CLOSE
{ CurrentSemanticValue.lg = new Not(ValueStack[ValueStack.Depth-2].lg);	}
        break;
      case 8: // simplePositiveUnaryTests -> simplePositiveUnaryTest
{ CurrentSemanticValue.lg = ValueStack[ValueStack.Depth-1].lg;							}
        break;
      case 9: // simplePositiveUnaryTests -> simplePositiveUnaryTests, COMMA, 
              //                             simplePositiveUnaryTest
{ CurrentSemanticValue.lg = new Or(ValueStack[ValueStack.Depth-3].lg, ValueStack[ValueStack.Depth-1].lg);				}
        break;
      case 10: // simplePositiveUnaryTests -> OP_MINUS
{ CurrentSemanticValue.lg = new BooleanLiteral(true);	}
        break;
      case 12: // simplePositiveUnaryTest -> simplePositiveUnaryTestOp, endpoint
{ CurrentSemanticValue.lg = new Comparison(ValueStack[ValueStack.Depth-2].co, ValueStack[ValueStack.Depth-1].nd, new InputValue()); }
        break;
      case 13: // simplePositiveUnaryTest -> intervalStart, endpoint, RANGE, endpoint, 
               //                            intervalEnd
{ CurrentSemanticValue.lg = new Range(ValueStack[ValueStack.Depth-5].b, ValueStack[ValueStack.Depth-1].b, ValueStack[ValueStack.Depth-4].nd, ValueStack[ValueStack.Depth-2].nd, new InputValue()); }
        break;
      case 15: // intervalStart -> openIntervalStart
{ CurrentSemanticValue.b = true; }
        break;
      case 16: // intervalStart -> SP_OPEN
{ CurrentSemanticValue.b = false; }
        break;
      case 21: // intervalEnd -> openIntervalEnd
{ CurrentSemanticValue.b = true; }
        break;
      case 22: // intervalEnd -> SP_CLOSE
{ CurrentSemanticValue.b = false; }
        break;
      case 27: // simplePositiveUnaryTestOp -> C_LT
{ CurrentSemanticValue.co = ComparisonOperator.LessThan;			  }
        break;
      case 28: // simplePositiveUnaryTestOp -> C_LE
{ CurrentSemanticValue.co = ComparisonOperator.LessThanOrEqual;	  }
        break;
      case 29: // simplePositiveUnaryTestOp -> C_GT
{ CurrentSemanticValue.co = ComparisonOperator.GreaterThan;		  }
        break;
      case 30: // simplePositiveUnaryTestOp -> C_GE
{ CurrentSemanticValue.co = ComparisonOperator.GreaterThanOrEqual; }
        break;
      case 32: // endpoint -> simpleValue
{ CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 34: // simpleValue -> simpleLiteral
{ CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 35: // simpleValue -> qualifiedName
{ CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].qn; }
        break;
      case 37: // simpleLiteral -> numericLiteral
{ CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 38: // simpleLiteral -> stringLiteral
{ CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 39: // simpleLiteral -> booleanLiteral
{ CurrentSemanticValue.nd = ValueStack[ValueStack.Depth-1].nd; }
        break;
      case 41: // numericLiteral -> NUMBER
{ CurrentSemanticValue.nd = new NumericLiteral(ValueStack[ValueStack.Depth-1].n); }
        break;
      case 43: // stringLiteral -> STRING
{ CurrentSemanticValue.nd = new StringLiteral(ValueStack[ValueStack.Depth-1].s); }
        break;
      case 45: // booleanLiteral -> BOOLEAN
{ CurrentSemanticValue.nd = new BooleanLiteral(ValueStack[ValueStack.Depth-1].b); }
        break;
      case 47: // qualifiedName -> NAME
{ CurrentSemanticValue.qn = new QualifiedName(ValueStack[ValueStack.Depth-1].s);		}
        break;
      case 48: // qualifiedName -> qualifiedName, DOT, NAME
{ CurrentSemanticValue.qn = ValueStack[ValueStack.Depth-3].qn;	CurrentSemanticValue.qn.AddComponent(ValueStack[ValueStack.Depth-1].s);	}
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Token)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Token)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


// The use code section.
// It is empty, because use code goes in a partial class.
}
}
